import { PrismaClient } from "@prisma/client";
import * as argon2 from "argon2";
import { config } from "dotenv";
import { mkdir, rename, writeFile } from "node:fs/promises";
import path from "node:path";

config({ path: path.resolve(__dirname, "../../../.env") });

import {
  formatHtpasswdLine,
  serializeHtpasswd,
} from "../src/permissions/htpasswd.util";

const prisma = new PrismaClient();

function getWorkspaceRoot(): string {
  return path.resolve(__dirname, "../../..");
}

function resolveDataPath(relativePath: string): string {
  return path.resolve(getWorkspaceRoot(), relativePath);
}

async function writeAuthzPlaceholder(): Promise<void> {
  const authzPath = resolveDataPath(
    process.env.SVN_AUTHZ_PATH ?? "data/svn-authz",
  );
  await mkdir(path.dirname(authzPath), { recursive: true });
  const content = [
    "# Generated by SVNHUB — do not edit manually",
    `# ${new Date().toISOString()}`,
    "",
  ].join("\n");
  const tmpPath = `${authzPath}.tmp`;
  await writeFile(tmpPath, content, "utf8");
  await rename(tmpPath, authzPath);
}

function resolveAdminPassword(): string {
  const password =
    process.env.ADMIN_INITIAL_PASSWORD ?? process.env.SERVICE_PASSWORD_ADMIN;

  if (password) {
    return password;
  }

  if (process.env.NODE_ENV === "production") {
    throw new Error(
      "Set ADMIN_INITIAL_PASSWORD or SERVICE_PASSWORD_ADMIN before seeding in production",
    );
  }

  return "Admin@123";
}

async function main(): Promise<void> {
  const email = process.env.ADMIN_EMAIL ?? "admin@svnhub.local";
  const username = process.env.ADMIN_USERNAME ?? "admin";
  const password = resolveAdminPassword();
  const displayName = process.env.ADMIN_DISPLAY_NAME ?? "SVNHUB Admin";

  const passwordHash = await argon2.hash(password);

  const user = await prisma.user.upsert({
    where: { email },
    update: {
      username,
      displayName,
      passwordHash,
      isLocal: true,
      isAdmin: true,
    },
    create: {
      email,
      username,
      displayName,
      passwordHash,
      isLocal: true,
      isAdmin: true,
    },
  });

  const passwdPath = resolveDataPath(
    process.env.SVN_PASSWD_PATH ?? "data/svn-passwd",
  );
  await mkdir(path.dirname(passwdPath), { recursive: true });
  const htpasswdContent = serializeHtpasswd(
    new Map([[username, formatHtpasswdLine(username, password).split(":")[1]!]]),
  );
  const passwdTmp = `${passwdPath}.tmp`;
  await writeFile(passwdTmp, htpasswdContent, "utf8");
  await rename(passwdTmp, passwdPath);

  await writeAuthzPlaceholder();

  await mkdir(resolveDataPath(process.env.SVN_REPOS_ROOT ?? "data/repos"), {
    recursive: true,
  });
  await mkdir(resolveDataPath("data/artifacts"), { recursive: true });
  await mkdir(resolveDataPath("data/avatars"), { recursive: true });

  console.log("SVNHUB seed completed.");
  console.log(`Admin user: ${user.email} (username: ${user.username})`);

  if (process.env.NODE_ENV !== "production") {
    console.log(`Admin password: ${password}`);
  } else if (process.env.SERVICE_PASSWORD_ADMIN) {
    console.log(
      "Admin password: see SERVICE_PASSWORD_ADMIN in Coolify environment variables",
    );
  } else {
    console.log("Admin password: configured via ADMIN_INITIAL_PASSWORD");
  }

  console.log("Use the same username/password for SVN checkout via Apache.");
}

main()
  .catch((error) => {
    console.error(error);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
