export interface AuthzGroup {
  name: string;
  members: string[];
}

export interface AuthzPathRule {
  path: string;
  entries: Array<{
    principal: string;
    access: "r" | "rw" | "";
  }>;
}

export interface AuthzRepoSection {
  repoSlug: string;
  rules: AuthzPathRule[];
}

export interface AuthzCompileInput {
  groups: AuthzGroup[];
  repos: AuthzRepoSection[];
}

export function compileAuthz(input: AuthzCompileInput): string {
  const lines: string[] = [
    "# Generated by SVNHUB — do not edit manually",
    "# " + new Date().toISOString(),
    "",
  ];

  if (input.groups.length > 0) {
    lines.push("[groups]");
    for (const group of input.groups) {
      const members = group.members.filter(Boolean).join(", ");
      lines.push(`${group.name} = ${members}`);
    }
    lines.push("");
  }

  for (const repo of input.repos) {
    for (const rule of repo.rules) {
      const sectionPath = rule.path === "/" ? "/" : rule.path.replace(/\/+$/, "");
      lines.push(`[${repo.repoSlug}:${sectionPath}]`);

      const seen = new Set<string>();
      for (const entry of rule.entries) {
        if (!entry.principal || seen.has(entry.principal)) continue;
        seen.add(entry.principal);
        if (entry.access === "") {
          lines.push(`${entry.principal} =`);
        } else {
          lines.push(`${entry.principal} = ${entry.access}`);
        }
      }
      lines.push("");
    }
  }

  return lines.join("\n").trimEnd() + "\n";
}

export function pathAccessToAuthz(access: "READ" | "WRITE" | "NONE"): "r" | "rw" | "" {
  switch (access) {
    case "READ":
      return "r";
    case "WRITE":
      return "rw";
    case "NONE":
      return "";
  }
}

export function repoRoleDefaultAccess(role: string): "r" | "rw" {
  switch (role) {
    case "OWNER":
    case "MAINTAINER":
      return "rw";
    case "DEVELOPER":
    case "READER":
    default:
      return "r";
  }
}

export function formatPrincipal(
  principalType: "USER" | "GROUP",
  name: string,
): string {
  return principalType === "GROUP" ? `@${name}` : name;
}
