import apr1 from "apache-md5";

export function hashHtpasswdPassword(password: string): string {
  return apr1(password);
}

export function formatHtpasswdLine(username: string, password: string): string {
  return `${username}:${hashHtpasswdPassword(password)}`;
}

export function parseHtpasswd(content: string): Map<string, string> {
  const entries = new Map<string, string>();

  for (const line of content.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) {
      continue;
    }

    const separator = trimmed.indexOf(":");
    if (separator <= 0) {
      continue;
    }

    const username = trimmed.slice(0, separator);
    const hash = trimmed.slice(separator + 1);
    entries.set(username, hash);
  }

  return entries;
}

export function serializeHtpasswd(entries: Map<string, string>): string {
  const lines = [
    "# Generated by SVNHUB — do not edit manually",
    `# ${new Date().toISOString()}`,
    "",
    ...Array.from(entries.entries())
      .sort(([left], [right]) => left.localeCompare(right))
      .map(([username, hash]) => `${username}:${hash}`),
    "",
  ];

  return lines.join("\n");
}
