#!/bin/sh
set -eu

data_root="${SVN_DATA_ROOT:-}"

if [ -n "$data_root" ]; then
  mkdir -p "$data_root/repos" "$data_root/artifacts"
  chown -R www-data:www-data "$data_root/repos"

  if [ ! -f "$data_root/svn-passwd" ]; then
    touch "$data_root/svn-passwd"
  fi
  if [ ! -f "$data_root/svn-authz" ]; then
    printf '%s\n' \
      '# Generated by SVNHUB — placeholder until API rebuilds authz' \
      "# $(date -u +%Y-%m-%dT%H:%M:%SZ)" \
      > "$data_root/svn-authz"
  fi

  chown www-data:www-data "$data_root/svn-passwd" "$data_root/svn-authz"
  chmod 640 "$data_root/svn-passwd" "$data_root/svn-authz"

  rm -rf /var/svn/repos
  ln -s "$data_root/repos" /var/svn/repos
  ln -sf "$data_root/svn-passwd" /etc/apache2/dav_svn.passwd
  ln -sf "$data_root/svn-authz" /etc/apache2/svn-authz
else
  mkdir -p /var/svn/repos
  chown -R www-data:www-data /var/svn/repos

  if [ ! -f /etc/apache2/dav_svn.passwd ]; then
    touch /etc/apache2/dav_svn.passwd
    chown www-data:www-data /etc/apache2/dav_svn.passwd
    chmod 640 /etc/apache2/dav_svn.passwd
  fi

  if [ ! -f /etc/apache2/svn-authz ]; then
    printf '%s\n' \
      '# Generated by SVNHUB — placeholder until API rebuilds authz' \
      "# $(date -u +%Y-%m-%dT%H:%M:%SZ)" \
      > /etc/apache2/svn-authz
    chown www-data:www-data /etc/apache2/svn-authz
    chmod 640 /etc/apache2/svn-authz
  fi
fi

exec apache2ctl -D FOREGROUND
